package com.sv.gauge.server_model;
// Generated Mar 25, 2016 2:28:59 PM by Hibernate Tools 4.3.1


/**
 * Transaction generated by hbm2java
 */
public class Transaction implements java.io.Serializable {
    private Integer id;
    private int domainId;
    private String domainName;
    private String reportDescription;
    private int currentStepId;
    private String date;
    private String startTime;
    private String endTime;
    private String userName;
    private int userId;
    private String status;

    public Transaction() {
    }

    public Transaction(int domainId, int currentStepId, int userId) {
        this.domainId = domainId;
        this.currentStepId = currentStepId;
        this.userId = userId;
    }

    public Transaction(int domainId, String domainName, String reportDescription, int currentStepId, String date, String startTime, String endTime, String userName, int userId, String status) {
        this.domainId = domainId;
        this.domainName = domainName;
        this.reportDescription = reportDescription;
        this.currentStepId = currentStepId;
        this.date = date;
        this.startTime = startTime;
        this.endTime = endTime;
        this.userName = userName;
        this.userId = userId;
        this.status = status;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public int getDomainId() {
        return this.domainId;
    }

    public void setDomainId(int domainId) {
        this.domainId = domainId;
    }

    public String getDomainName() {
        return this.domainName;
    }

    public void setDomainName(String domainName) {
        this.domainName = domainName;
    }

    public String getReportDescription() {
        return this.reportDescription;
    }

    public void setReportDescription(String reportDescription) {
        this.reportDescription = reportDescription;
    }

    public int getCurrentStepId() {
        return this.currentStepId;
    }

    public void setCurrentStepId(int currentStepId) {
        this.currentStepId = currentStepId;
    }

    public String getDate() {
        return this.date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getStartTime() {
        return this.startTime;
    }

    public void setStartTime(String startTime) {
        this.startTime = startTime;
    }

    public String getEndTime() {
        return this.endTime;
    }

    public void setEndTime(String endTime) {
        this.endTime = endTime;
    }

    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public int getUserId() {
        return this.userId;
    }

    public void setUserId(int userId) {
        this.userId = userId;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }
}


