package com.sv.gauge.server_model;
// Generated Mar 28, 2016 3:13:00 PM by Hibernate Tools 4.3.1


/**
 * User generated by hbm2java
 */

public class User implements java.io.Serializable {


    private Integer id;
    private String name;
    private String username;
    private String password;
    private Boolean isAdmin;

    public User() {
    }

    public User(String name, String username, String password, Boolean isAdmin) {
        this.name = name;
        this.username = username;
        this.password = password;
        this.isAdmin = isAdmin;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public Boolean getIsAdmin() {
        return this.isAdmin;
    }

    public void setIsAdmin(Boolean isAdmin) {
        this.isAdmin = isAdmin;
    }

}


